### PR TITLE
Added synops counter

### PR DESCRIPTION
**Pull request by Jegp**
Implements #355

### CODE REVIEW

**Comment by cpehle** [comment]
Do you know weather this. has a performance impact? I would rather solve this with something like a forward hook.

**Comment by Jegp** [comment]
If the flag is not set, it'd be minimal because the initialization happens in the constructor. If the flag is set, however, I suspect it'll be costly. But, well. I guess that's the point :-)

Regarding using a forward hook for this, that may actually be possible, although the code would be slightly more convoluted. The way I could see this working would be to invert the control: offer a function that takes a module as input and sets the necessary buffers + hooks. Something like 

```def register_synops_hook(module: torch.nn.Module): ...

net = norse.torch.SequentialState(...)
register_synops_hook(net)
```

Would that be preferable?

**Comment by cpehle** [comment]
I think so yes. This is not something that is so central to the function of the library that it should be hard coded into the control flow, but rather added on as needed. One way to do this would be some kind of forward hook or other "profiling" type operation.

**Comment by Jegp** [comment]
Closed, c.f. https://github.com/norse/norse/issues/355

**Pull request closed without merging**
