### PR TITLE
Feature filter

### PR DESCRIPTION
**Pull request by Pugavkomm**
Added exponential smoothing function and exponential smoothing layer.

### CODE REVIEW

**Review by Jegp — CHANGES_REQUESTED** [review]
Thanks for this contribution! I like the way you added detailed documentation and type annotations.  

The (unrelated) tests are somehow failing. I'll look into that and possibly shove it in this PR if that's ok.

I would, though, really appreciate it if you could write at least two rudimentary tests (in the `./test` directory) to ensure that 1) the function/module will run and 2) that the numerical output is somewhat as expected. Just so we're certain that the code will work future changes. Makes it much easier to maintain.

**Comment by Pugavkomm** [comment]
OK. I will add tests today or tomorrow.

**Review by cpehle — APPROVED** [review]
LGTM. Jens will you look into why the tests are failing? Could you please also address the trailing whitespace issues: https://app.codacy.com/gh/norse/norse/pullRequest?prid=8501132. You can easily do so by using ```black``` to format the new files.

**Comment by Jegp** [comment]
It's unlikely I'll find time to merge it today, unfortunately. Fixes for the tests are in the #275 PR, so this should be quick to merge

**Comment by Jegp** [comment]
Hey, and thanks for the changes @Pugavkomm !

**Comment by Pugavkomm** [comment]
It should be everything.

**Review by Jegp — APPROVED** [review]

**Comment by Jegp** [comment]
Thanks a lot for seeing this through @Pugavkomm!

**Pull request merged**
