### PR TITLE
Added pytree state and support for torch.compile

### PR DESCRIPTION
**Pull request by Jegp**
This PR serves as place to discuss adding functionality to states. It's meant to partially address #181, improve usability, and slowly start having a crack at #200.

Concretely, I'm suggesting that we adds functions to states that lets us _almost_ treat them as tensors, while retaining support for Python's native Tuples as used in PyTorch's JIT'ing and ONNX.
The code will let us reformulate states as:

```python
from norse.torch.utils.pytree import StateTuple, MultipleInheritanceNamedTupleMeta
class LIFState(StateTuple, metaclass=MultipleInheritanceNamedTupleMeta):
    z: torch.Tensor
    v: torch.Tensor
    i: torch.Tensor
```

Which lets users do stuff like the following:
```python
s = LIFState(z=torch.as_tensor(0.0), v=torch.as_tensor(-65.0), i=torch.as_tensor(0.0))
s.to("cuda") # Move all tensors to cuda
s.int() # Convert all tensors to int
s.float() # Convert all tensors to float
s.broadcast(torch.empty(10, 20)) # Broadcast to shape of the given tensor
```

Note that this also works with default values and numeric members, although they won't be touched since they're outside the scope of PyTorch.

If there is support for this, we can roll it out to the states in the various models.

### CODE REVIEW

**Comment by Jegp** [comment]
Do you think this is worth-while to pursue @cpehle?

**Comment by cpehle** [comment]
I would say generally speaking this is a good approach, as long as it is compatible with jit compilation. We should perhaps do a hackathon style pass through the codebase and identify all obstacles to jit compilation, then this would make sense to look at.

**Comment by cpehle** [comment]
Overall I think this is a good approach, I've used something similar in JAX. Depending on the tree_math library. This lets you do things like

```python
from norse.base.types import ArrayLike
import dataclasses


@dataclasses.dataclass
@tree_math.struct
class SynapseState:
    a: ArrayLike
    b: ArrayLike

@dataclasses.dataclass
@tree_math.struct
class SynapseParameters:
    tau_r: ArrayLike
    tau_d: ArrayLike
    g_max: ArrayLike
    gamma: ArrayLike = 0.062
    e: ArrayLike = 0.0
    mg: ArrayLike = 0.0
    mg_dep: ArrayLike = 3.57

def dynamics(s: SynapseState, p: SynapseParameters):
    return SynapseState(a=-1 / p.tau_r * s.a, b=-1 / p.tau_d * s.b)
```

Naturally express the dynamics in terms of variables.

**Comment by Jegp** [comment]
New changes includes support for `torch.compile` as a replacement for jit compilation for lif functions and modules. Note that I removed the default parameter values in the lif functional methods. It breaks the jit compilation, and I don't think it's a big problem to remove it because (1) users rarely use the functionals and (2) the modules still provide defaults.

The new pytree object is left in the tree, but breaks the dynamo compilation. But I suggest we merge it as-is and then build on it later.

**Comment by Jegp** [comment]
The pytree NamedTuple compile issues are related to https://github.com/pytorch/pytorch/issues/91662 btw

**Pull request merged**
