### PR TITLE
Added governance document

### PR DESCRIPTION
**Pull request by Jegp**
Added a governance document to increase transparency, and to ensure the continued thriving and development of Norse.

The document is fairly simple, but designed to easily be extended.

Comments are (as always) welcome!

### CODE REVIEW

**Comment by cpehle** [comment]
Before we commit to such a governance document, can we maybe briefly review how these things are done in other open-source projects of this size? I feel like some of these things are handled by the LICENSE and copyright law, i.e. since we have not required anyone to sign a license agreement and so they retain their copyright. Moreover the LICENSE clearly specifies under which circumstances code can be used and modified. What hasn't explicitly been done is for example create a trademark / copyright for the "Norse" brand. We also haven't explicitly publicly assigned roles, but the de-facto ownership in of the Norse organisation / who has write access to the repository hasn't changed.

**Comment by cpehle** [comment]
Given that you unilaterally revoked my owner status of the organisation. I don't see this governance document as a good faith effort anymore. This has gone beyond something that can be reasonably resolved without involvement of a third-party, which is why I suggest we talk to for example an ombudsman of one of our universities.

**Comment by Jegp** [comment]
In a private conversation, you told me you considered yourself the sole author and owner of Norse. I created this repo/organisation to create open and accessible software infrastructure that is not owned by any individual. This is is basically just me making sure that we have equal ownership, so Norse stays accessible to scientists around the world.

I completely understand if you would like to include third parties. Although,  I don't see any conflict if you agree on the general trends in the governance document.

**Comment by cpehle** [comment]
I think it is best if we continue most of this discussion privately. I disagree with your characterisation of what I asserted and in any case it is not a justification for your actions.

Regarding copyright: This is not an issue that we can resolve with such a document. The majority of the contributions I did are copyright University of Heidelberg, because I was employed there at the time (and still am). Even though a lot of the original code I contributed has been refactored / slightly modified most of it is I think still derivative work. So just legally this copyright is probably owned by the University of Heidelberg. It was apparently a mistake to not clearly assign authorship and copyright on a per file basis and since so far there doesn't exist a legal entity that would be able to "own" Norse, current ownership lies with the copyright holders (of the original, non-derivative contributions). If you are serious about sorting this out, it will probably be a pretty long and arduous task.

**Comment by Jegp** [comment]
> Regarding copyright: This is not an issue that we can resolve with such a document. The majority of the contributions I did are copyright / owned by University of Heidelberg, because I was employed there at the time (and still am). Even though a lot of the original code I contributed has been refactored / slightly modified most of it is I think still derivative work. So just legally this copyright is probably owned by the University of Heidelberg. It was apparently a mistake to not clearly assign authorship and copyright on a per file basis and since so far there doesn't exist a legal entity that would be able to "own" Norse, current ownership lies with the copyright holders (of the original, non-derivative contributions). Of course you and a few others also have done original contributions, so the ownership of the library code right now is distributed among those copyright holders. If you are serious about sorting this out, it will probably be a pretty long and arduous task.

I am ready to put Norse out in the public domain, but it occurs to me that you are not. That is basically the conflict. If this is not the case, and you agree with "freeing" Norse, we can easily find a path forward, I'm sure.

Currently, all my work is my own IP. I understand that is not the case for you. Since we have joint ownership, claiming that Norse is owned by Heidelberg is simply not true. I do not know which claims Heidelberg have, but perhaps there are some ways to open source IP in the Heidelberg?

> What I am concerned about is that this governance document would be non-legally binding and potentially misleading, which is why I suggest we continue to resolve this conflict privately, before moving on with a final decision on such a document.

Happy to resolve this privately. I have tried, and will continue to try, to find a peaceful solution to this. The PR was submitted after you gave a tentative consent for parts of the content. I was under the impression that it only needed minor revisions.

**Comment by cpehle** [comment]
I did not claim that Norse is owned by Heidelberg. Please read carefully again. I said that the original contributions of all authors are owned by them. I also mentioned the concept of derivative work, which does not result in a transfer of ownership . The concept of public domain does not exist in the context of German copyright law. As I said it will be arduous to sort out the ownership under copyright law, afterwards a decision can be made by the copyright holders on transferring ownership to some other legal entity.

**Comment by Jegp** [comment]
> I did not claim that Norse is owned by Heidelberg. 

You wrote "Even though a lot of the original code I contributed has been refactored / slightly modified most of it is I think still derivative work." ... "So just legally this copyright is probably owned by the University of Heidelberg.". How can that be interpreted differently? Isn't this exactly saying "My work is Norse, everyone else did derivative work"?

> I don't have any issues with this document as is, it is just that I doubt that it resolves the very real and now apparently pressing legal questions as it is legally non-binding and would not prevent future bad faith actions. From my perspective the combination of copyright law, which unfortunately we did not properly discuss, as we did not explicitly assign authorship and copyright to individual files and the choice of LICENSE (LGPL-v3), which is a legally binding document under which contributions are made (although we probably need to make this more explicit), covers most of the questions of _code_ ownership.

If we both agree to a document, it is legally binding. Just like a verbal agreement is legally binding. The governance document would be a tentative way to place notion of ownership in the hands of the committee. That would free us from our squabble and hopefully allow us to move forward with the pretty neat ideas inherent in Norse. Now, there may be questions about your IP from Heidelberg, which I'm not familiar with.

> As I said it will be arduous to sort out the ownership under copyright law, afterwards a decision can be made by the copyright holders on transferring ownership to some other legal entity (which would need to be created).

It will be tremendously arduous. That is why I suggest we simply agree to share ownership 50/50 (until others may want to get involved). Unfortunately, I'm afraid our concept of "who has the right to what" is divergent. If we cannot agree to share access/control/GitHub equally, I don't see any other way than to arduously credit each of us individually.

**Comment by cpehle** [comment]
What I am saying is that even though I did not think this was necessary before, the only way to resolve this is to go through every file, find agreement on authorship and ownership, document this agreement and move on. 
> Isn't this exactly saying "My work is Norse, everyone else did derivative work"?
No this is saying everything in Norse which is a derivative work of my original work is still something I own the copyright to, at least that is my current legal understanding, which might well be incorrect. I explicitly mentioned now several times, that you and others have done original contributions. I happily and deliberately put my original contribution under LGPL-v3, but this is separate from code *ownership*.

**Comment by Jegp** [comment]
Given that Norse is under LGPL, under which we both have been deliberately working for quite a while now, I suggest closing this issue, hoping that we won't have to resolve any issue of ownership anytime in the future :-)

**Pull request closed without merging**
