### PR TITLE
Fix[ci] spack (concretization of py-torch)

### PR DESCRIPTION
**Pull request by muffgaga**
Variant `cudnn` isn't available without variant `cuda` being active…

### CODE REVIEW

**Review by cpehle — APPROVED** [review]

**Comment by muffgaga** [comment]
Hmm, ok, then I fixed a bug which we do not yet see in the CI here…

**Comment by muffgaga** [comment]
The fails in "Documentation Build / Build documentation" seem to be unrelated to this change…?

**Comment by muffgaga** [comment]
Ok, 2h40min until the error in building PyTorch ;)… (I hope that the cache works.)

```
2022-06-24T19:01:35.5118593Z   [4340/4944] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o
2022-06-24T19:01:35.5119183Z   FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o
2022-06-24T19:01:35.5142102Z   /tmp/tmp.G1Hx4KCtd2/spack/lib/spack/env/gcc/g++ -DADD_BREAKPAD_SIGNAL_HANDLER -DAT_PER_OPERATOR_HEADERS -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DFXDIV_USE_INLINE_ASSEMBLY=0 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/aten/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/aten/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/caffe2/contrib/aten -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/onnx -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/third_party/onnx -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/foxi -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/third_party/foxi -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc/api -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc/api/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/caffe2/aten/src/TH -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/caffe2/aten/src/TH -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/caffe2/aten/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/caffe2/../third_party -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/caffe2/../third_party/breakpad/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/caffe2/../aten/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/miniz-2.0.8 -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/kineto/libkineto/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/kineto/libkineto/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc/distributed -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/aten/../third_party/catch/single_include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/aten/src/ATen/.. -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/caffe2/core/nomnigraph/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/FXdiv/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/c10/.. -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/cpuinfo/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/QNNPACK/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/aten/src/ATen/native/quantized/cpu/qnnpack/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/aten/src/ATen/native/quantized/cpu/qnnpack/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/cpuinfo/deps/clog/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/NNPACK/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/fbgemm/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/fbgemm -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/fbgemm/third_party/asmjit/src -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/FP16/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/fmt/include -I/tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/flatbuffers/include -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/protobuf-3.18.0-53s2x7bqyb4vnlw3kvwjtmtgr5dfb4v2/include -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/openblas-0.3.20-pf3a6vbztknrzjoe2d7ptucunbibrwkc/include -isystem /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/gemmlowp -isystem /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/neon2sse -isystem /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/third_party/XNNPACK/include -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/numactl-2.0.14-lspspol6y2nnx43tn7g2mg5ol3lvow74/include -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/eigen-3.4.0-k4hgreosi64m6o3bxxviv4wrkodlprz2/include/eigen3 -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/python-3.9.12-ge3l6shqr5ijggl2bofa6nf3a34lcxns/include/python3.9 -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/py-numpy-1.22.4-tj3x466zxw2kbzm3ku4aq3ro6s4hrq55/lib/python3.9/site-packages/numpy/core/include -isystem /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/cmake/../third_party/pybind11/include -isystem /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/build/include -isystem /home/runner/.spack-cache/install/linux-ubuntu20.04-x86_64_v4/gcc-10.3.0/zlib-1.2.12-2ddhvsvvfwnqk2q7lh4tenp2so34rev3/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -fPIC -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-type-limits -Wno-array-bounds -Wno-sign-compare -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-missing-braces -Wno-maybe-uninitialized -fvisibility=hidden -O2 -fopenmp -DCAFFE2_BUILD_MAIN_LIB -pthread -DASMJIT_STATIC -std=gnu++14 -MD -MT caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o -MF caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o.d -o caffe2/CMakeFiles/torch_cpu.dir/__/torch/csrc/jit/ir/ir.cpp.o -c /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc/jit/ir/ir.cpp
2022-06-24T19:01:42.8633348Z   /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc/jit/ir/ir.cpp: In member function 'bool torch::jit::Node::hasSideEffects() const':
2022-06-24T19:01:42.8635013Z   /tmp/runner/spack-stage/spack-stage-py-torch-1.11.0-qyeg2k6qd5ro6hnn3ubshfghgq2gnzkt/spack-src/torch/csrc/jit/ir/ir.cpp:1194:16: error: 'set_stream' is not a member of 'torch::jit::cuda'; did you mean 'c10::cuda::set_stream'?
2022-06-24T19:01:42.8635639Z    1194 |     case cuda::set_stream:
2022-06-24T19:01:42.8635968Z         |                ^~~~~~~~~~
```

The error looks like a cuda dependency issue (configure flow not properly disabling cuda or something) → for now I try to restore CI by pinning to an older version of PyTorch (<1.11).

**Comment by Jegp** [comment]
> Ok, 2h40min until the error in building PyTorch ;)… (I hope that the cache works.)

:scream: Is there any way to reduce that? Perhaps by caching?

**Comment by muffgaga** [comment]
> > Ok, 2h40min until the error in building PyTorch ;)… (I hope that the cache works.)
> scream Is there any way to reduce that? Perhaps by caching?

Added commit enabling build caching… let's see if it works.

**Comment by Jegp** [comment]
That seems to do it!

The build time is still massive. But I imagine the caching should kick in for subsequent builds.

Are you happy with this so far @muffgaga? Can we go ahead and GTM? :moneybag:

**Comment by muffgaga** [comment]
And the switch to the older `arch` invalidated the cache entries again… so a full rebuild is being done :grimacing:.

**Comment by muffgaga** [comment]
@Jegp @cpehle The path to the build cache is still wrong :/… but I will fix this in another PR (to avoid another full rebuild).

**Comment by Jegp** [comment]
That makes sense. For now, this resolves the failing build, so that's a step in the right direction.

Thanks yet again @muffgaga! :)

**Pull request merged**
